import "./globals.css";
import AuthProvider from "@/context/auth-provider";
import Navbar from "@/components/navbar";
import { ToastProvider } from "@/context/toast-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastProvider />
          <Navbar />
          <div className="mx-auto p-2 max-w-7xl gap-2 mb-10 border border-slate-700 ">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
